SET FOREIGN_KEY_CHECKS = 0;

DROP TABLE IF EXISTS aircraft;
DROP TABLE IF EXISTS airport;
DROP TABLE IF EXISTS booking;
DROP TABLE IF EXISTS company;
DROP TABLE IF EXISTS flight;
DROP TABLE IF EXISTS flight_log;
DROP TABLE IF EXISTS passenger;
DROP TABLE IF EXISTS passport;
DROP TABLE IF EXISTS ticket;

SET FOREIGN_KEY_CHECKS = 1;