SET FOREIGN_KEY_CHECKS = 0;

DROP TABLE IF EXISTS aircrafts;
DROP TABLE IF EXISTS airports;
DROP TABLE IF EXISTS bookings;
DROP TABLE IF EXISTS companies;
DROP TABLE IF EXISTS event_types;
DROP TABLE IF EXISTS flights;
DROP TABLE IF EXISTS flight_logs;
DROP TABLE IF EXISTS passengers;
DROP TABLE IF EXISTS passports;
DROP TABLE IF EXISTS tickets;

SET FOREIGN_KEY_CHECKS = 1;